// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4iMggGqNabVLp242DY5GhX5COpZ3bX_c',
    appId: '1:144007670192:web:56a71ca4aa090eda490e75',
    messagingSenderId: '144007670192',
    projectId: 'africtong-85f15',
    authDomain: 'africtong-85f15.firebaseapp.com',
    storageBucket: 'africtong-85f15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZtp1F6nVihr-tnfIuz9HahnxysZ_q88',
    appId: '1:144007670192:android:0450bbc89a08add1490e75',
    messagingSenderId: '144007670192',
    projectId: 'africtong-85f15',
    storageBucket: 'africtong-85f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJTeTh5ITKQ5xum6PqJ4wZ6qi9MGrKw5Y',
    appId: '1:144007670192:ios:0f519bc0aba24062490e75',
    messagingSenderId: '144007670192',
    projectId: 'africtong-85f15',
    storageBucket: 'africtong-85f15.appspot.com',
    iosBundleId: 'com.example.africtong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJTeTh5ITKQ5xum6PqJ4wZ6qi9MGrKw5Y',
    appId: '1:144007670192:ios:0f519bc0aba24062490e75',
    messagingSenderId: '144007670192',
    projectId: 'africtong-85f15',
    storageBucket: 'africtong-85f15.appspot.com',
    iosBundleId: 'com.example.africtong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4iMggGqNabVLp242DY5GhX5COpZ3bX_c',
    appId: '1:144007670192:web:943bf00eef50a3e7490e75',
    messagingSenderId: '144007670192',
    projectId: 'africtong-85f15',
    authDomain: 'africtong-85f15.firebaseapp.com',
    storageBucket: 'africtong-85f15.appspot.com',
  );
}
